server:
  port: 10086
eureka:
  client:
#    register-with-eureka: false # 是否注册自己的信息到EurekaServer，默认是true
#    fetch-registry: false # 是否拉取其它服务的信息，默认是true
    service-url: # EurekaServer的地址，现在是自己的地址，如果是集群，需要加上其它Server的地址。
      defaultZone: http://127.0.0.1:10086/eureka,http://127.0.0.1:10087/eureka
  server:
    eviction-interval-timer-in-ms: 30000 #心跳间隔（毫秒）默认90秒无心跳或则认为客户端宕机

spring:
  application:
    name: eureka-server #服务器名